name: WhatsApp Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Bot 
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GITTOKEN: ${{ secrets.GITTOKEN }} 
          ALWAYS_AUTO_DP: ${{ secrets.ALWAYS_AUTO_DP }} 
          ALWAYS_AUTO_BIO: ${{ secrets.ALWAYS_AUTO_BIO }} 
          SHOW_HOROSCOPE: ${{ secrets.SHOW_HOROSCOPE }} 
          ZODIAC_SIGN: ${{ secrets.ZODIAC_SIGN }} 
          CITY: ${{ secrets.CITY }} 
          IMAGE_URL: ${{ secrets.IMAGE_URL }} 
          AUTO_DP_INTERVAL_MS: ${{ secrets.AUTO_DP_INTERVAL_MS }} 
          TIME_ZONE: ${{ secrets.TIME_ZONE }} 
          AUTO_BIO_INTERVAL_MS: ${{ secrets.AUTO_BIO_INTERVAL_MS }} 
        run: npm start
